name: Build and Publish
on:
  push:
    branches:
      - gh-pages
      - main
      - publish_docs_workflow

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          python -m pip install --upgrade pip
          pip install tox
          tox -e docs

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}